tbl <- read.table("./tbl-macro-tcell.txt", as.is=TRUE, row.names=1)
tbl_bool <- (tbl > 0)
tbl_clean <- log10(tbl[rowSums(tbl_bool)> 10, ] + 1e-5)
m <- as.matrix(tbl_clean)
mpca <- prcomp(t(m))
# print(names(mpca))
# plot(mpca)
# print(mpca$x)
# print(mpca$rotation)
# print(dim(mpca$x))
# print(dim(mpca$rotation))
# plot(mpca$x[1:18,1:2], col='blue', ylim=c(min(mpca$x[,2]), max(mpca$x[,2])), xlim=c(min(mpca$x[,1]), max(mpca$x[,1])))
# points(mpca$x[19:28,1:2], col='orange')
# screeplot(mpca)

c1 <- kmeans(t(tbl_clean), centers=2)
m1 <- MASS::mvrnorm(n=100, mu=c(0,0), Sigma=matrix(c(2,0,0,1), nrow=2))
m2 <- MASS::mvrnorm(n=100, mu=c(3,3), Sigma=matrix(c(1,0,0,2), nrow=2))
# plot(m1, col='blue', xlim=c(-6,6), ylim=c(-6,6)); points(m2, col='red')
m12 <- rbind(m1,m2)
m12_cluster <- kmeans(m12, centers=2)
# plot(m12,col=m12_cluster$cluster, xlim=c(-6,6), ylim=c(-6,6))



names(tbl_clean) <- c(paste0('macro', seq(1,18)), paste0('t-cell', seq(1,10)))
d <- dist(t(tbl_clean))
hc <- hclust(d)
de <- as.dendrogram(hc)
plot(hc)
delist <- cut(de,400)
plot(delist$lower[[2]])